POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxYzE0Nzc3ZjBmYjU2NjFkMjA1YjQ1MSIsImlhdCI6MTY0MDgwNjQ4MH0.GnfoLfWNqNTdBfMqfRxbf13YRTpiWTXwXmOdO3GGHes

{
    "title": "419test",
    "author": "419test",
    "url": "http://localhost:3003/api/",
    "likes": 1
}

# POST http://localhost:3003/api/login 
# Content-Type: application/json

# {
#     "username": "root",
#     "password": "carrot"
# }