# POST http://localhost:3003/api/blogs
# Content-Type: application/json

# {
#     "title": "asdsdasda",
#     "author": "me",
#     "url": "test",
#     "likes": 444
# }

PUT http://localhost:3003/api/blogs/61b114b427e8d95e8fe9a6ff
Content-Type: application/json

{
    "title": "asdsdasda",
    "author": "me",
    "url": "no",
    "likes": 2
}